/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_Layout'
import { Route as ConsoleRouteRouteImport } from './routes/console/route'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as LayoutIndexRouteImport } from './routes/_Layout.index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as ConsoleContactsRouteRouteImport } from './routes/console/contacts/route'
import { Route as ConsoleContactsNewRouteImport } from './routes/console/contacts/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_Layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/_auth/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/_auth/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/_auth/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleContactsRouteRoute = ConsoleContactsRouteRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleContactsNewRoute = ConsoleContactsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ConsoleContactsRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/console': typeof ConsoleRouteRouteWithChildren
  '/console/contacts': typeof ConsoleContactsRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof LayoutIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/console/contacts/new': typeof ConsoleContactsNewRoute
}
export interface FileRoutesByTo {
  '/console/contacts': typeof ConsoleContactsRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof LayoutIndexRoute
  '/console': typeof ConsoleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/console/contacts/new': typeof ConsoleContactsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/console': typeof ConsoleRouteRouteWithChildren
  '/_Layout': typeof LayoutRouteWithChildren
  '/console/contacts': typeof ConsoleContactsRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_Layout/': typeof LayoutIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/console/contacts/new': typeof ConsoleContactsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/console'
    | '/console/contacts'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/'
    | '/console/'
    | '/api/auth/$'
    | '/console/contacts/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/console/contacts'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/'
    | '/console'
    | '/api/auth/$'
    | '/console/contacts/new'
  id:
    | '__root__'
    | '/console'
    | '/_Layout'
    | '/console/contacts'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_Layout/'
    | '/console/'
    | '/api/auth/$'
    | '/console/contacts/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_Layout': {
      id: '/_Layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_Layout/': {
      id: '/_Layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/contacts': {
      id: '/console/contacts'
      path: '/contacts'
      fullPath: '/console/contacts'
      preLoaderRoute: typeof ConsoleContactsRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/contacts/new': {
      id: '/console/contacts/new'
      path: '/new'
      fullPath: '/console/contacts/new'
      preLoaderRoute: typeof ConsoleContactsNewRouteImport
      parentRoute: typeof ConsoleContactsRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConsoleContactsRouteRouteChildren {
  ConsoleContactsNewRoute: typeof ConsoleContactsNewRoute
}

const ConsoleContactsRouteRouteChildren: ConsoleContactsRouteRouteChildren = {
  ConsoleContactsNewRoute: ConsoleContactsNewRoute,
}

const ConsoleContactsRouteRouteWithChildren = ConsoleContactsRouteRoute._addFileChildren(
  ConsoleContactsRouteRouteChildren,
)

interface ConsoleRouteRouteChildren {
  ConsoleContactsRouteRoute: typeof ConsoleContactsRouteRouteWithChildren
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleContactsRouteRoute: ConsoleContactsRouteRouteWithChildren,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(ConsoleRouteRouteChildren)

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren = LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
